load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Go rules
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.tar.gz"],
    sha256 = "<check_latest_sha256_from_release>",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains()

# Rust rules
http_archive(
    name = "rules_rust",
    urls = ["https://github.com/bazelbuild/rules_rust/archive/main.zip"],
    strip_prefix = "rules_rust-main",
)

# Python rules (typically come built-in with Bazel)
